name: .NET 6.0
on:
  #push:
    #branches: [ main ]
  pull_request:
    #branches: [ main ]

jobs:
  BuildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - uses: cryptic-wizard/run-specflow-tests@v1.3.1
      with:
        test-assembly-path: HexConverterTest/bin/Release/net6.0
        test-assembly-dll: HexConverterTest.dll
        output-html: HexConverterResults.html
        framework: net6.0